# Generated by Django 3.2.6 on 2021-09-09 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210909_1118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
